import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import mobileImage from '../../public/images/bg-sidebar-mobile.svg'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Image src={mobileImage} alt='sideBar image' className='w-full -z-10' priority/>
        {children}
        <Footer />
      </body>
    </html>
  )
}
